aeternity/elixir-node

- apps/aecore/lib/aecore/chain/worker.ex
- apps/aecore/lib/aecore/miner/worker.ex
- apps/aecore/lib/aecore/utils/blockchain/block_validation.ex
- apps/aecore/test/aecore_chain_test.exs
> [GH-#47] Refactor to not use all_blocks() in Miner

- apps/aecore/lib/aecore/miner/worker.ex
- apps/aecore/lib/aecore/structures/block.ex
- apps/aecore/lib/aecore/utils/blockchain/block_validation.ex
> [GH-#55] check block version in validation

- apps/aecore/lib/aecore/miner/worker.ex
- apps/aecore/lib/aecore/utils/blockchain/block_validation.ex
> [GH-#65] validate genesis block

- apps/aecore/lib/aecore/chain/chain_state.ex
- apps/aecore/lib/aecore/keys/worker.ex
- apps/aecore/lib/aecore/miner/worker.ex
- apps/aecore/lib/aecore/utils/blockchain/block_validation.ex
- apps/aecore/test/aecore_txs_pool_test.exs
- apps/aecore/test/multiple_transactions_test.exs
> [GH-#10] Include chainstate in checking transaction validity  

- apps/aecore/lib/aecore/chain/worker.ex
- apps/aecore/lib/aecore/peers/worker.ex
- apps/aecore/lib/aecore/utils/serialization.ex
- apps/aecore/test/aecore_serialization_test.exs
- apps/aehttpclient/lib/client.ex
- apps/aehttpserver/web/controllers/block_controller.ex
- apps/aehttpserver/web/router.ex
> GH-76 provide get_block_by_hash endpoint

- apps/aecore/lib/aecore/keys/worker.ex
- apps/aecore/lib/aecore/utils/blockchain/block_validation.ex
- apps/aecore/lib/aecore/utils/blockchain/difficulty.ex
> [GH-#72] Replaced term() with specific types where possible

- apps/aecore/lib/aecore/miner/worker.ex
- apps/aecore/lib/aecore/peers/worker.ex
- apps/aehttpclient/lib/client.ex
- apps/aehttpserver/web/controllers/peers_controller.ex
- apps/aehttpserver/web/router.ex
> GH-78 provide get all peers endpoint

- apps/aecore/lib/aecore/chain/chain_state.ex
- apps/aecore/lib/aecore/chain/worker.ex
- apps/aecore/lib/aecore/keys/worker.ex
- apps/aecore/lib/aecore/miner/worker.ex
- apps/aecore/lib/aecore/structures/tx_data.ex
- apps/aecore/lib/aecore/txs/pool/worker.ex
- apps/aecore/lib/aecore/utils/blockchain/block_validation.ex
- apps/aecore/test/aecore_chain_state_test.exs
- apps/aecore/test/aecore_keys_test.exs
- apps/aecore/test/aecore_tx_test.exs
- apps/aecore/test/aecore_txs_pool_test.exs
- apps/aecore/test/aecore_validation_test.exs
- apps/aecore/test/multiple_transactions_test.exs
> [GH-#70] Increment transaction nonce for every outgoing transaction

- apps/aehttpclient/lib/client.ex
- apps/aehttpserver/web/controllers/balance_controller.ex
- apps/aehttpserver/web/router.ex
> GH-89 endpoint to fetch balance from chainstate account

- apps/aecore/lib/aecore/keys/worker.ex
- apps/aecore/test/aecore_keys_test.exs
> GH-#84 Check public key length in transaction validity

- apps/aehttpserver/web/controllers/block_controller.ex
- apps/aehttpserver/web/router.ex
route for https://github.com/aeternity/web-wallet/issues/7
closes #147
> [GH-#147] get blocks route from_hash with count

- apps/aecore/lib/aecore/miner/worker.ex
- apps/aecore/lib/aecore/peers/sync.ex
- apps/aecore/lib/aecore/peers/worker.ex
do not merge before #142 
closes #113
> [GH-113] Sync worker state functions

- apps/aecore/lib/aecore/chain/block_validation.ex
- apps/aecore/lib/aecore/structures/signed_tx.ex
- apps/aecore/lib/aecore/txs/pool/worker.ex
- apps/aecore/test/aecore_tx_test.exs
- apps/aecore/test/aecore_txs_pool_test.exs
> [GH-#168] make negative transactions invalid

- apps/aehttpserver/lib/aehttpserver/web/controllers/info_controller.ex
> [GH-#173] fixed issue with getting /info not as node

- .credo.exs
- apps/aecore/lib/aecore/chain/chain_state.ex
- apps/aecore/lib/aecore/chain/worker.ex
- apps/aecore/test/aecore_chain_test.exs
- apps/aecore/test/multiple_transactions_test.exs
- apps/aehttpserver/lib/aehttpserver/web/controllers/info_controller.ex
addresses #174 suggestion from @untra
> [GH-#173] don't reuse variable names, addressed @untra comment

- apps/aecore/lib/aecore/chain/worker.ex
- apps/aecore/lib/aecore/txs/pool/worker.ex
- apps/aehttpserver/config/config.exs
- apps/aehttpserver/lib/aehttpserver/web/channels/notification_channel.ex
- apps/aehttpserver/lib/aehttpserver/web/channels/notify.ex
- apps/aehttpserver/lib/aehttpserver/web/channels/user_socket.ex
- apps/aehttpserver/lib/aehttpserver/web/endpoint.ex
> [GH-#183] Websocket interface

- apps/aecore/lib/aecore/miner/worker.ex
> [GH-#219] update block candidate every 500 nonces

- apps/aecore/lib/aecore/chain/chain_state.ex
> [GH-#224] refactored chain_state calculation

- apps/aecore/lib/aecore/wallet/worker.ex
> [GH-#249] only save pub_key with "" derivation path to state

- apps/aecore/lib/aecore/chain/worker.ex
- apps/aecore/lib/aecore/persistence/worker.ex
- apps/aecore/lib/aecore/structures/block.ex
- apps/aecore/lib/aecore/structures/signed_tx.ex
- apps/aecore/lib/aecore/txs/pool/worker.ex
- apps/aecore/lib/aecore/wallet/worker.ex
> [GH-#266] fixed compiler warnings

- .travis.yml
> [GH-#271] make ci fail on compiler warnings

- apps/aecore/config/config.exs
- apps/aecore/lib/aecore/structures/spend_tx.ex
- apps/aeutil/test/aeutil_serialization_test.exs
resolves #281 
Will be merged to #280 which will merge both the issues (#280 and #281) with the master branch
> [GH-#281] Added version field in the SpendTx module structure

- apps/aecore/lib/aecore/chain/worker.ex
- apps/aecore/lib/aecore/structures/spend_tx.ex
> [GH-#297] initialize unknown accounts empty, fixed undefined function

- apps/aecore/lib/aecore/chain/chain_state.ex
- apps/aecore/lib/aecore/structures/data_tx.ex
- apps/aecore/test/aecore_tx_test.exs
- apps/aehttpclient/lib/client.ex
- apps/aehttpserver/lib/aehttpserver/web/controllers/miner_controller.ex
> [GH-#299] Fixes a bug where an invalid transaction would be mined

- apps/aeutil/lib/serialization.ex
- apps/aeutil/test/aeutil_serialization_test.exs
> [GH-#257] Adjusted block serialization/deserialization

- apps/aecore/lib/aecore/peers/sync.ex
> [GH-#311] Fixed wrong GenServer handle call atom

- apps/aecore/lib/aecore/chain/worker.ex
- apps/aecore/lib/aecore/peers/sync.ex
resolves #296 
Also renamed the chain_sync key to be chain_sync_status as it was before.
> [GH-#296] Fixing the transasction pattern matching problem in chain_state

- apps/aehttpserver/lib/aehttpserver/web/controllers/block_controller.ex
> [GH-313] Fixed HTTP server endpoint bug

- apps/aehttpserver/config/dev.exs
> [GH-#338] Fixed the dev port

- apps/aecore/lib/aecore/account/account.ex
- apps/aecore/lib/aecore/chain/chainstate.ex
- apps/aecore/test/aecore_chain_state_test.exs
- apps/aecore/test/aecore_oracle_test.exs
- apps/aecore/test/multiple_transactions_test.exs
> [GH-#346] Add height of last update to one accounts state

- apps/aeutil/lib/scientific.ex
- apps/aeutil/test/aeutil_scientific_test.exs
> [GH-#356] Adeed target to difficulty calculation

- apps/aecore/lib/aecore/chain/worker.ex
> [GH-#360] Removed the struct from the maps when checked for empty

- README.md
> [GH-#362] adjust readme

- apps/aecore/lib/aecore/tx/data_tx.ex
> [GH-#383] Reversed order of argument in deduct_fee function

- apps/aecore/test/aecore_oracle_test.exs
> [GH-#389] resolve CI still failing at oracle tests in some cases

- apps/aecore/lib/aecore/tx/data_tx.ex
- apps/aecore/test/aecore_serializations_test.exs
> [GH-#422] Reordered and adjusted pattern-matching bindings in DataTx rlp decodings

- mix.exs
> [GH-#424] Using aeternity enacl repo

- apps/aehttpserver/lib/aehttpserver/web/controllers/balance_controller.ex
> [GH-#430] fix broken /balance endpoint

- mix.exs
- mix.lock
> [GH-#438] Fixed wallet dependency to use a specific ref

- apps/aecore/lib/aecore/chain/worker.ex
> [GH-#446] Fixed incorrectly persisted chainstate

- .travis.yml
- apps/aecore/lib/aecore/tx/pool/worker.ex
> [GH-#353] fix unreachable xrefs and added to travis

- apps/aecore/lib/aecore/peers/peer_connection.ex
- apps/aecore/lib/aecore/peers/worker.ex
- apps/aehttpclient/lib/client.ex
- apps/aehttpserver/lib/aehttpserver/web/controllers/peers_controller.ex
- apps/aehttpserver/lib/aehttpserver/web/router.ex
> [GH-#440] add peer info helper endpoint

- apps/aecore/lib/aecore/account/account_state_tree.ex
> [GH-#460] Fixed wrong AccountStateTree.get/2 specification

- apps/aecore/lib/aecore/tx/data_tx.ex
> [GH-#455] Fixed NameUpdateTx RLP decoding

- README.md
> [GH-#472] Make peers readme section clearer

- apps/aehttpserver/lib/aehttpserver/web/controllers/balance_controller.ex
> [GH-#461] Fixed problem with getting account balance 

- apps/aecore/lib/aecore/account/account_state_tree.ex
- apps/aecore/lib/aecore/naming/naming_state_tree.ex
- apps/aecore/lib/aecore/oracle/oracle_state_tree.ex
> [GH-#480] Added function root_hash for Naming and Oracle Trees

- apps/aecore/lib/aecore/chain/block.ex
- apps/aecore/test/aecore_serializations_test.exs
> [GH-#485] Fixed RLP tests

- apps/aecore/lib/aecore/chain/chainstate.ex
> [GH-#453] Root chainstate hash

- apps/aecore/lib/aecore/chain/block_validation.ex
- mix.exs
[This closes #488](https://github.com/aeternity/elixir-node/issues/488)
> [GH-#488] Replace tx hash gb_tree with patricia merkle tree

- apps/aeutil/lib/serialization.ex
- mix.exs
> [GH-#459] remove unused dependencies

- apps/aecore/lib/aecore/chain/worker.ex
- apps/aecore/lib/aecore/persistence/worker.ex
- apps/aecore/test/aecore_persistence_test.exs
- mix.exs
> [GH-#466] Fixed bug where we can't get blocks out of memory

- apps/aecore/config/dev.exs
- apps/aecore/lib/aecore/chain/block_validation.ex
> [GH-#504] Adjusted min_fee configuration

- apps/aehttpclient/lib/client.ex
> [GH-#498] Removed unused functions from http client

- apps/aecore/lib/aecore/chain/block.ex
- apps/aecore/lib/aecore/oracle/tx/oracle_extend_tx.ex
- apps/aecore/test/aecore_serializations_test.exs
- apps/aecore/test/test_utils.ex
Details:
- Fixed transaction deserialization in block serialization. (proper handling of return value)
- Added transaction to tested block in serialization test
This fixes #536
> [GH-536] Bug in block serialization

- apps/aecore/lib/aecore/peers/peer_connection.ex
> [GH-#546] Fixed p2p protocol verison

- Makefile
> [GH-#548] Fixed makefile signpeers directory name

- apps/aecore/lib/aecore/account/account.ex
- apps/aecore/lib/aecore/account/tx/spend_tx.ex
- apps/aecore/lib/aecore/chain/chainstate.ex
- apps/aecore/lib/aecore/chain/header.ex
- apps/aecore/lib/aecore/chain/identifier.ex
- apps/aecore/lib/aecore/channel/channel_state_on_chain.ex
- apps/aecore/lib/aecore/naming/name_claim.ex
- apps/aecore/lib/aecore/naming/name_commitment.ex
- apps/aecore/lib/aecore/naming/tx/name_claim_tx.ex
- apps/aecore/lib/aecore/naming/tx/name_pre_claim_tx.ex
- apps/aecore/lib/aecore/naming/tx/name_revoke_tx.ex
- apps/aecore/lib/aecore/naming/tx/name_transfer_tx.ex
- apps/aecore/lib/aecore/naming/tx/name_update_tx.ex
- apps/aecore/lib/aecore/oracle/oracle.ex
- apps/aecore/lib/aecore/oracle/tx/oracle_extend_tx.ex
- apps/aecore/lib/aecore/oracle/tx/oracle_query_tx.ex
- apps/aecore/lib/aecore/oracle/tx/oracle_registration_tx.ex
- apps/aecore/lib/aecore/oracle/tx/oracle_response_tx.ex
- apps/aecore/lib/aecore/tx/data_tx.ex
- apps/aecore/lib/aecore/tx/signed_tx.ex
> [GH-530] Replaced all t() with their full name in the same module

- apps/aecore/lib/aecore/channel/channel_state_on_chain.ex
- apps/aecore/lib/aecore/channel/channel_state_peer.ex
- apps/aecore/lib/aecore/naming/name_commitment.ex
- apps/aecore/lib/aecore/oracle/oracle.ex
- apps/aecore/lib/aecore/oracle/oracle_query.ex
- apps/aeutil/mix.exs
- dialyzer.ignore-warnings
> [GH-529] Fixed wrong specifications

- apps/aehttpserver/lib/aehttpserver/web/controllers/peers_controller.ex
> [GH-569] changed peer atom for get_info_try_connect

- apps/aecore/lib/aecore/chain/block_validation.ex
- apps/aecore/lib/aecore/tx/signed_tx.ex
> [GH-571] Adjusted calculate_txs_hash logic

- apps/aecore/lib/aecore/chain/chainstate.ex
> [GH-575-new] Fixed order of transaction root hash in calculating

- apps/aecore/lib/aecore/governance/governance_constants.ex
- apps/aecore/lib/aecore/naming/tx/name_claim_tx.ex
> [GH-579] Added name_claim_burned_fee and fixed total fee of NameClaimTx

- apps/aecore/test/aecore_channels_test.exs
- apps/aetestframework/lib/worker.ex
- apps/aetestframework/test/multi_node_sync_test.exs
> [GH-590] Adjust the Multinode Test Framework to check the pool and mined txs

- apps/aecore/lib/aecore/oracle/oracle.ex
- apps/aecore/lib/aecore/oracle/tx/oracle_extend_tx.ex
- apps/aecore/lib/aecore/oracle/tx/oracle_response_tx.ex
- apps/aecore/lib/aecore/tx/pool/worker.ex
- apps/aecore/test/aecore_oracle_test.exs
- apps/aetestframework/lib/worker.ex
> [GH-588] Adjusted oracle transactions 

- apps/aecore/lib/aecore/naming/tx/name_update_tx.ex
> [GH-593] Fixed name_update_tx

- apps/aetestframework/lib/worker.ex
- apps/aetestframework/test/multi_node_sync_test.exs
> [GH-599] Fix the test framework crashes in travis CI

- apps/aecore/lib/aecore/oracle/oracle_query.ex
This fixes a merge issue introduced by #352 in oracles.
> [GH-352] Fix merge issue in oracles

- apps/aecore/lib/aecore/peers/peer_connection.ex
- apps/aecore/lib/aecore/peers/worker.ex
> [GH-607] Added Logger.error() if Peers.try_connect() fails

- apps/aecore/lib/aecore/oracle/oracle.ex
- apps/aecore/lib/aecore/oracle/tx/oracle_query_tx.ex
- apps/aecore/lib/aecore/oracle/tx/oracle_registration_tx.ex
> [GH-613] fix oracle relative/absolute tll incorrect functions

- apps/aeutil/lib/patricia_merkle_tree.ex
- apps/aeutil/test/patricia_merkle_tree_test.exs
> [GH-609] Fixed Aeutil.PatriciaMerkleTree insert func

- .travis.yml
> [GH-628] Removed mix dialyzer from Travis

- README.md
- docs/aeternity-erlang-compatibility.md
> [GH-545] added aeternity erlang compatibility doc

- apps/aecore/lib/aecore/chain/chainstate.ex
- apps/aecore/lib/aecore/tx/data_tx.ex
- apps/aecore/lib/aecore/tx/signed_tx.ex
- mix.lock
> [GH-626] removed top_block reference from validation

- apps/aecore/lib/aecore/oracle/tx/oracle_query_tx.ex
> [GH-632] remove chain usage from oracle_query_tx

- apps/aecore/lib/aecore/account/account.ex
- apps/aecore/lib/aecore/account/account_state_tree.ex
- apps/aecore/lib/aecore/channel/channel_off_chain_tx.ex
- apps/aecore/lib/aecore/channel/channel_off_chain_update.ex
- apps/aecore/lib/aecore/channel/channel_state_on_chain.ex
- apps/aecore/lib/aecore/channel/channel_state_peer.ex
- apps/aecore/lib/aecore/channel/channel_transaction.ex
- apps/aecore/lib/aecore/channel/tx/channel_create_tx.ex
- apps/aecore/lib/aecore/channel/updates/channel_create_update.ex
- apps/aecore/lib/aecore/channel/updates/channel_deposit_update.ex
- apps/aecore/lib/aecore/channel/updates/channel_transfer_update.ex
- apps/aecore/lib/aecore/channel/updates/channel_widthdraw_update.ex
- apps/aecore/lib/aecore/channel/worker.ex
- apps/aecore/lib/aecore/poi/poi.ex
- apps/aecore/lib/aecore/poi/poi_proof.ex
- apps/aecore/lib/aecore/tx/signed_tx.ex
- apps/aecore/test/aecore_channels_test.exs
- apps/aecore/test/aecore_poi_epoch_compatibility_and_functional_test.exs
- apps/aeutil/lib/patricia_merkle_tree.ex
- apps/aeutil/test/patricia_merkle_tree_test.exs
Refactored channel updates, channel adjustments, removed redundant data
> [GH-533] Refactored channel updates, channel adjustments, removed redundant data

- apps/aecore/lib/aecore/chain/chainstate.ex
> [GH-654] Use channels root hash in chainstate hash

- .travis.yml
- apps/aecore/lib/aecore/chain/block_validation.ex
- apps/aecore/lib/aecore/tx/pool/worker.ex
> [GH-640] Added check if txs minimum fees are met when validating a block

- .dockerignore
- .gitignore
- Makefile
> [GH-657] add make all-test target, to locally run checks done by ci

- apps/aecore/lib/aecore/account/account.ex
- apps/aecore/test/aecore_chain_state_test.exs
- apps/aecore/test/aecore_naming_test.exs
- apps/aecore/test/aecore_serializations_test.exs
- apps/aecore/test/aecore_txs_pool_test.exs
- apps/aecore/test/aecore_validation_test.exs
- apps/aecore/test/multiple_transactions_test.exs
- apps/aecore/test/test_utils.ex
- apps/aehttpclient/test/aehttpclient_test.exs
- apps/aetestframework/lib/worker.ex
> [GH-652] Automatically added spend_tx and naming txs to the pool upon creation

- apps/aecore/config/dev.exs
- apps/aecore/lib/aecore/account/tx/spend_tx.ex
- apps/aecore/lib/aecore/chain/block_validation.ex
- apps/aecore/lib/aecore/chain/worker.ex
- apps/aecore/lib/aecore/channel/tx/channel_close_mutal_tx.ex
- apps/aecore/lib/aecore/channel/tx/channel_close_solo_tx.ex
- apps/aecore/lib/aecore/channel/tx/channel_create_tx.ex
- apps/aecore/lib/aecore/channel/tx/channel_settle_tx.ex
- apps/aecore/lib/aecore/channel/tx/channel_slash_tx.ex
- apps/aecore/lib/aecore/governance/governance_constants.ex
- apps/aecore/lib/aecore/miner/worker.ex
- apps/aecore/lib/aecore/naming/tx/name_claim_tx.ex
- apps/aecore/lib/aecore/naming/tx/name_pre_claim_tx.ex
- apps/aecore/lib/aecore/naming/tx/name_revoke_tx.ex
- apps/aecore/lib/aecore/naming/tx/name_transfer_tx.ex
- apps/aecore/lib/aecore/naming/tx/name_update_tx.ex
- apps/aecore/lib/aecore/oracle/oracle.ex
- apps/aecore/lib/aecore/oracle/tx/oracle_extend_tx.ex
- apps/aecore/lib/aecore/oracle/tx/oracle_query_tx.ex
- apps/aecore/lib/aecore/oracle/tx/oracle_registration_tx.ex
- apps/aecore/lib/aecore/oracle/tx/oracle_response_tx.ex
- apps/aecore/lib/aecore/tx/pool/worker.ex
- apps/aecore/test/aecore_oracle_test.exs
closes #633, closes #634, closes #641, closes #643, closes #650
The biggest change out of these is the change to is_minimum_fee_met? in all transaction modules, the rest are pretty small but important fixes
> [GH-633, GH-634, GH-641, GH-643, GH-650] Various oracle related adjustments

- apps/aecore/lib/aecore/chain/chainstate.ex
- apps/aecore/lib/aecore/oracle/tx/oracle_extend_tx.ex
- apps/aecore/lib/aecore/oracle/tx/oracle_query_tx.ex
- apps/aecore/lib/aecore/oracle/tx/oracle_registration_tx.ex
- apps/aecore/lib/aecore/oracle/tx/oracle_response_tx.ex
- apps/aecore/lib/aecore/tx/data_tx.ex
- apps/aecore/lib/aecore/tx/signed_tx.ex
- apps/aecore/lib/aecore/tx/transaction.ex
> [GH-635][GH-659] use is_minimum_fee_met callback for all transactions implicitly

- apps/aehttpclient/test/aehttpclient_test.exs
> [GH-666] AeHttpClient test stability fix

- apps/aecore/config/config.exs
> [GH-672] "Secret" -> "secret"

- apps/aecore/lib/aecore/account/account_state_tree.ex
- apps/aecore/lib/aecore/channel/channel_state_tree.ex
- apps/aecore/lib/aecore/contract/call_state_tree.ex
- apps/aecore/lib/aecore/contract/contract_state_tree.ex
- apps/aecore/lib/aecore/naming/name.ex
- apps/aecore/lib/aecore/naming/name_commitment.ex
- apps/aecore/lib/aecore/naming/naming_state_tree.ex
- apps/aecore/lib/aecore/util/state_trees.ex
- apps/aecore/test/aecore_contract_test.exs
- apps/aecore/test/aecore_naming_test.exs
> [GH-656] Adjusted code duplication between state trees

- apps/aecore/lib/aecore/sync/sync.ex
I'm not sure if my changes are correct, but they fixed syncing problems for me. 
This fixes #671
> [GH-671] Fixed sync with 3 or more nodes

- docs/aeternity-erlang-compatibility.md
> [GH-638] Channel compatibility testing docs

- docs/aeternity-erlang-compatibility.md
> [GH-681] Updated aeternity-erlang-compatibility documentation

- apps/aecore/lib/aecore/peers/worker.ex
> [GH-683] Fixed error message when Peers.try_connect() 

- .travis.yml
- apps/aetestframework/mix.exs
> [GH-687] always recompile project in CI, fix compile errors

- apps/aecore/lib/aecore/chain/identifier.ex
- apps/aecore/lib/aecore/channel/tx/channel_close_mutal_tx.ex
- apps/aecore/lib/aecore/channel/tx/channel_close_solo_tx.ex
- apps/aecore/lib/aecore/channel/tx/channel_create_tx.ex
- apps/aecore/lib/aecore/channel/tx/channel_settle_tx.ex
- apps/aecore/lib/aecore/channel/tx/channel_slash_tx.ex
> [GH-685] Added additional identifier checks

- apps/aecore/lib/aecore/contract/call.ex
- apps/aecore/lib/aecore/contract/dispatch.ex
- apps/aecore/lib/aecore/contract/tx/contract_create_tx.ex
> [GH-700] Made contract create tx compatible to Epoch protocol. 

- apps/aecore/lib/aecore/contract/tx/contract_call_tx.ex
- apps/aecore/lib/aecore/contract/tx/contract_create_tx.ex
- apps/aecore/lib/aecore/tx/data_tx.ex
- apps/aecore/lib/aecore/tx/transaction.ex
> [GH-709] Remove reference to Chain.chain_state() in ContractCallTx

- apps/aecore/lib/aecore/contract/tx/contract_call_tx.ex
- apps/aecore/test/aecore_contract_test.exs
- apps/aevm/lib/aevm.ex
Call contract tx is now being successfully synced with epoch as well.
Resolves #707
> [GH-707] Adjust contract_call_tx function

- docs/release-notes/release-notes-0.1.0.md
> [GH-778] Add dependencies to release notes
